from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from vulnmngsys_app.services.scanflow.remediation_logger import log_reconfig_event

IIS_SERVICES = ["W3SVC", "IISADMIN", "WMSvc", "MsDepSvc", "WsusService", "HTTP"]


def _text(value: Any) -> str:
    return str(value or "").strip()


def _ps(value: Any) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def _failed_results(report: dict[str, Any], selected_cves: list[str] | None) -> list[dict[str, Any]]:
    selected = {cve.upper() for cve in selected_cves or [] if cve}
    rows = []
    for row in report.get("results") or []:
        cves = [str(cve).upper() for cve in row.get("cve") or []]
        status = _text(row.get("status")).upper()
        if status not in {"FAIL", "WARNING", "ERROR"}:
            continue
        if selected and not selected.intersection(cves):
            continue
        rows.append(row)
    return rows


@dataclass(frozen=True)
class IisRemediationPlan:
    script_path: Path
    selected_count: int
    cves: list[str]

    def payload(self) -> dict[str, Any]:
        return {
            "scriptPath": str(self.script_path),
            "selected": self.selected_count,
            "cves": self.cves,
        }


class IisRemediationPlanner:
    def build_plan(
        self,
        report: dict[str, Any],
        app_root: Path,
        selected_cves: list[str] | None = None,
    ) -> IisRemediationPlan:
        rows = _failed_results(report, selected_cves)
        out_dir = app_root / "reports" / "reconfig"
        out_dir.mkdir(parents=True, exist_ok=True)
        script_path = out_dir / "vulnmngsys_iis_cve_reconfig.ps1"
        cves = sorted({cve for row in rows for cve in row.get("cve", [])})
        script_path.write_text("\n".join(self._script_lines(rows)) + "\n", encoding="utf-8")
        return IisRemediationPlan(script_path=script_path, selected_count=len(rows), cves=cves)

    def _script_lines(self, rows: list[dict[str, Any]]) -> list[str]:
        lines = [
            "# Generated by VulnMngSys. Review patch plan before applying on production.",
            "$ErrorActionPreference = 'Stop'",
            "$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()",
            "if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { "
            "throw 'Run as Administrator.' }",
            "$transcriptPath = Join-Path $env:TEMP 'vulnmngsys_iis_cve_reconfig_transcript.log'",
            "Start-Transcript -Path $transcriptPath -Force",
            "",
        ]
        if not rows:
            lines += ["Write-Output 'No failed IIS CVE findings selected for remediation.'", "Stop-Transcript"]
            return lines

        lines += [
            "Write-Output 'IIS CVE remediation is patch-led.'",
            "Write-Output 'Install the required Microsoft cumulative updates or approved offline KB packages.'",
            "Write-Output 'Then rerun the IIS CVE audit.'",
            "",
        ]
        for row in rows:
            local = row.get("local_check_result") or {}
            lines += [
                f"# {', '.join(row.get('cve') or [])}: {_text(row.get('name'))}",
                f"Write-Output {_ps(local.get('patch_guidance') or row.get('remediation') or 'Apply vendor patch.')}",
                f"Write-Output {_ps('Patch baseline: ' + _text(local.get('patch_after') or '-'))}",
                "",
            ]
        lines += ["Stop-Transcript"]
        return lines


class IisPowerShellExecutor:
    def run(self, script_path: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(script_path)],
            capture_output=True,
            text=True,
            timeout=900,
            check=False,
        )


class IisRemediationPipeline:
    def __init__(self, *, backup=None, verifier=None, executor: IisPowerShellExecutor | None = None) -> None:
        self.backup = backup
        self.verifier = verifier
        self.executor = executor or IisPowerShellExecutor()
        self.planner = IisRemediationPlanner()

    def preview(
        self,
        report: dict[str, Any],
        app_root: Path,
        selected_cves: list[str] | None = None,
    ) -> dict[str, Any]:
        plan = self.planner.build_plan(report, app_root, selected_cves)
        payload = {"ok": True, "requiresReview": True, **plan.payload()}
        log_reconfig_event(app_root, "iis_reconfig_preview", payload)
        return payload

    def apply(
        self,
        report: dict[str, Any],
        app_root: Path,
        selected_cves: list[str] | None = None,
    ) -> dict[str, Any]:
        if self.backup is None or self.verifier is None:
            raise ValueError("IIS remediation apply requires backup and verifier dependencies.")

        plan = self.planner.build_plan(report, app_root, selected_cves)
        backup_id = self.backup.trigger_backup(plan.cves)
        before_status = self.verifier.get_services_status(IIS_SERVICES)
        result = self.executor.run(plan.script_path)
        stable = self.verifier.verify_after_fix(before_status)
        should_rollback = result.returncode != 0 or not stable
        rolled_back = False
        if should_rollback:
            self.backup.rollback_config(backup_id)
            rolled_back = True

        payload = {
            "ok": result.returncode == 0 and stable,
            "autoRolledBack": rolled_back,
            "backupId": backup_id,
            "backupPath": str(self.backup.backup_path(backup_id)) if hasattr(self.backup, "backup_path") else "",
            **plan.payload(),
            "stdout": (result.stdout or "").strip(),
            "stderr": (result.stderr or "").strip(),
            "exitCode": result.returncode,
            "serviceWarnings": [{"message": "IIS-related service stopped; rollback was triggered."}]
            if rolled_back
            else [],
        }
        log_reconfig_event(app_root, "iis_reconfig_apply", payload)
        return payload
